sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: TphoQhf6/Wej7FFyVP9UG+Dr2s0DLB4qONGutb4UbAPesXoSDYiP4qkp8u+KUTCkrddGvASFC6pan+wyk7sRWMkAjkNsHMt1oVKm/MBQZVw4wjeIdn3n0G108t/dP02lw/FY2CmyVsPaISdWl9GemRwbuB3V0+YSMVqxla+nev4ZtXStDffFt1Q3sm2gHjmWxs7l/CPg05YtHtSi/cvz1yFD8V5K8zkivUvWeBwAWOfjOfZaqfX4M+LwRtZ2ODq01ff6rf/Szjppwnr2UiXnruqCVI22Xnq7oz7aArQ1cNaDFDGkE0UAb4K6GHd2h+eTU2cwuqjUQslA1D6Skx79tTUDaXZWjv3N9XspADNediPl1o91dGwgQBwPyLQhCg0bpDbZ2P3J8kns7nt49YH6MrEjcC1TXsLKZqJdKz4nuW/YQ1CS15jWrqwe0v99J57arefxEmnIDFu7LDibzQlhvBvJ9MfSi8RTtChVHKKZk1t8eKOiICoO+GeOq+3A8CYcGyIaXpxVAw52IPlm/MUMsf1Bqo2L6U8uKbOP4ViyjjKKbTx2pgMDUik7x+KHbxxLdK/A/+DuT7Q5tkrnEMLnHQBPIY1Bq3EHrJOGpGZSPTdzqWMjDmjyZL2fZ1DIeabIeZDpBnikkqMYMhtIC/wqbZVXChNmfaTVqaVD2lJNLG8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Cymbeline_1799
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy